import Sidebar from "@/components/Sidebar";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { SidebarRoutes } from "@/config/routes";
import { ToastProvider } from "@/providers/ToastProvider";
import SidebarProvider from "@/providers/SidebarProvider";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} max-w-[120rem] mx-auto`}>
        <ToastProvider />
        <main className="h-full border w-full flex ">
          <SidebarProvider />
          <section>{children}</section>
        </main>
      </body>
    </html>
  );
}
