import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ToastProvider } from "@/providers/ToastProvider";
import SidebarProvider from "@/providers/SidebarProvider";
import { NextUiProviders } from "@/providers/NextUIProvider";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} max-w-[120rem] mx-auto`}>
        <ToastProvider />
        <NextUiProviders>
          <main className="w-full flex border ">
            <SidebarProvider />
            <section className="flex-1">{children}</section>
          </main>
        </NextUiProviders>
      </body>
    </html>
  );
}
