/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "eu-north-1",
  aws_cognito_identity_pool_id:
    "eu-north-1:4b5b4441-9c7c-4dd5-88da-f0b310e140ca",
  aws_cognito_region: "eu-north-1",
  aws_user_pools_id: "eu-north-1_gTlo5XPPd",
  aws_user_pools_web_client_id: "569sj0dj25lmb29smila3lssl8",
  oauth: {},
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: [],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [
      "REQUIRES_LOWERCASE",
      "REQUIRES_NUMBERS",
      "REQUIRES_SYMBOLS",
      "REQUIRES_UPPERCASE",
    ],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_user_files_s3_bucket: "sthlm-east-storage-7c245c11173242-staging",
  aws_user_files_s3_bucket_region: "eu-north-1",
};

export default awsmobile;
